name = "longpro-scaffold"
main = "src/index.js"
compatibility_date = "2026-03-07"
compatibility_flags = ["nodejs_compat"]
workers_dev = false
preview_urls = false

[assets]
binding = "ASSETS"
directory = "./dist_assets"
html_handling = "auto-trailing-slash"
not_found_handling = "404-page"
run_worker_first = true

[observability]
enabled = true

[[routes]]
pattern = "longpropc.com"
custom_domain = true

[[routes]]
pattern = "www.longpropc.com"
custom_domain = true
